export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_STATS = 'FETCH_STATS';
export const FETCH_BRANCHES = 'FETCH_BRANCHES';
export const FETCH_LIST_OF_BRANCHES = 'FETCH_LIST_OF_BRANCHES';