//AUTH
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

//BRANCHES
export const FETCH_BRANCHES = 'FETCH_BRANCHES';
export const FETCH_BRANCH = 'FETCH_BRANCH';
export const UPDATE_BRANCH = 'UPDATE_BRANCH';
export const ADD_BRANCH = 'ADD_BRANCH';

//GROUPS
export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_GROUP = 'FETCH_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const ADD_GROUP = 'ADD_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const CHANGE_GROUP_STATUS = 'CHANGE_GROUP_STATUS';

//COMMON
export const ERROR = 'ERROR';
export const FETCH_ERROR = 'FETCH_ERROR';

//ROLES
export const FETCH_ROLES = 'FETCH_ROLES';
export const FETCH_ROLE = 'FETCH_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const ADD_ROLE = 'ADD_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';
export const CHANGE_ROLE_STATUS = 'CHANGE_ROLE_STATUS';

//USERS
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER = 'FETCH_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS';