//COMMON
export const GENERAL_ERROR = 'GENERAL_ERROR';
export const FETCH_ERROR = 'FETCH_ERROR';
export const CONFIRM_NOTIFICATION = 'CONFIRM_NOTIFICATION';

//AUTH
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

//BRANCHES
export const FETCH_BRANCHES = 'FETCH_BRANCHES';
export const FETCH_BRANCH = 'FETCH_BRANCH';
export const UPDATE_BRANCH = 'UPDATE_BRANCH';
export const ADD_BRANCH = 'ADD_BRANCH';

//GROUPS
export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_GROUP = 'FETCH_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const ADD_GROUP = 'ADD_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const CHANGE_GROUP_STATUS = 'CHANGE_GROUP_STATUS';

//ROLES
export const FETCH_ROLES = 'FETCH_ROLES';
export const FETCH_ROLE = 'FETCH_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const ADD_ROLE = 'ADD_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';
export const CHANGE_ROLE_STATUS = 'CHANGE_ROLE_STATUS';

//USERS
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER = 'FETCH_USER';
export const SEARCH_USERS = 'SEARCH_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS';

//TICKETS
export const FETCH_TICKETS = 'FETCH_TICKETS';
export const FETCH_TICKET = 'FETCH_TICKET';
export const SEARCH_TICKETS = 'SEARCH_TICKETS';
export const UPDATE_TICKET = 'UPDATE_TICKET';

//MESSAGES
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGE = 'FETCH_MESSAGE';
export const SEARCH_MESSAGES = 'SEARCH_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';

//STATISTICS
export const FETCH_USERS_STATS = 'FETCH_USERS_STATS';
export const FETCH_MESSAGES_STATS = 'FETCH_MESSAGES_STATS';
export const FETCH_GROUPS_STATS = 'FETCH_GROUPS_STATS';
export const FETCH_TICKETS_STATS = 'FETCH_TICKETS_STATS';
export const FETCH_PERMISSIONS_STATS = 'FETCH_PERMISSIONS_STATS';
export const SET_USERS_CHARTS_STYLE = 'SET_USERS_CHARTS_STYLE';
export const SET_MESSAGES_CHARTS_STYLE = 'SET_MESSAGES_CHARTS_STYLE';
export const SET_GROUPS_CHARTS_STYLE = 'SET_GROUPS_CHARTS_STYLE';
export const SET_TICKETS_CHARTS_STYLE = 'SET_TICKETS_CHARTS_STYLE';
export const SET_PERMISSIONS_CHARTS_STYLE = 'SET_PERMISSIONS_CHARTS_STYLE';

//TODO implement DELETE functionality in Private API during refactoring
export const UNDONE_MESSAGE = 'UNDONE_MESSAGE';