export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_BRANCHES = 'FETCH_BRANCHES';
export const FETCH_SINGLE_BRANCH = 'FETCH_SINGLE_BRANCH';